package app.exceptions;

public class CustomerNotFountException extends RuntimeException{
    public CustomerNotFountException(Throwable cause) {
        super(cause);
    }
}
